name: teb_janelajohari
description: Janela de Johari.
publish_to: 'none'

version: 1.0.5+270

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  teb_package:
    #git:
    #  url: https://github.com/marcosmhs/teb_package.git
    #  ref: main
    path: ../teb_package
  
  build_runner: ^2.4.6
  intl: ^0.19.0
  flutter_localization: ^0.1.13
  
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.0.1
  firebase_database: ^11.0.1
  firebase_analytics: ^11.0.1
  
  url_launcher: ^6.1.14
  http: ^1.2.1
  scroll_to_index: ^3.0.1
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.8.0
  flutter_colorpicker: ^1.1.0

  
  shared_preferences: ^2.2.2

  flutter_lints: ^5.0.0
  firebase_data_connect: ^0.1.4
  firebase_core: ^3.13.0
  flutter_html: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/theme.json
    - assets/images/logo.png
    - assets/images/logo_black.png